
name: workflow2

on:
    workflow_dispatch:

jobs:
    push-jobs:
        runs-on: ubuntu-latest

        steps:
        - name: checkout repository
          uses: actions/checkout@v2

        - name: make changes
          run: |
             git config --global user.email "arshankar1999@gmail.com"
             git config --global user.name "Ravi Arumilli"

             echo "New Changes" >> changes.txt
             git add changes.txt
             gir commit -m "Add Changes"

        - name: push changes
          env: 
            GITHUB_TOKEN: ${{secrets.Ar_clasic_token}}
          run: |
            git push origin feature-branch
